 -- 웬만하면 함수 첫번째 매개변수 위치에는 COLUMN명이 들어간다고 보면 됨

-- 문자열 함수
SELECT 'HELLO WORLD' FROM DUAL; -- DUAL = SQL문을 간단하게 연습하기 위한 가상의 테이블
SELECT LOWER ('HELLO WORLD') FROM DUAL;
SELECT LOWER (FIRST_NAME), UPPER(FIRST_NAME), INITCAP(FIRST_NAME) FROM EMPLOYEES;

-- LENGTH 문자열 길이
SELECT FIRST_NAME, LENGTH (FIRST_NAME) FROM EMPLOYEES ORDER BY LENGTH (FIRST_NAME) DESC;

-- INSTR 문자열 찾기
SELECT FIRST_NAME, INSTR (FIRST_NAME, 'a') FROM EMPLOYEES; -- a가 있는 위치를 반환함 , 없으면 0을 반환함

-- SUBSTR 문자열 자르기
SELECT FIRST_NAME, SUBSTR (FIRST_NAME, 3) FROM EMPLOYEES; -- 3번째 위치부터 잘라옴
SELECT FIRST_NAME, SUBSTR (FIRST_NAME, 3), SUBSTR (FIRST_NAME, 3, 2) FROM EMPLOYEES; --3번째 위치를 기점으로 두번째 위치까지 잘라옴

-- CONCAT 문자열 합치기
SELECT FIRST_NAME ||' '|| LAST_NAME, CONCAT(FIRST_NAME,LAST_NAME) FROM EMPLOYEES;

-- LPAD, RPAD 범위를 지정하고 특정문자로 채움
SELECT 'ABC' FROM DUAL;
SELECT LPAD ('ABC', 10, '*') FROM DUAL; -- ABC길이를 10까지 늘리고 비어 있는 왼쪽 자리는 *로 채움
SELECT LPAD (FIRST_NAME, 10, '*') FROM EMPLOYEES;
SELECT RPAD (FIRST_NAME, 10, '*') FROM EMPLOYEES;

-- LTRIM, RTRIM. TRIM : 공백 삭제 또는 문자 삭제
SELECT TRIM('     HELLO WORLD     ') FROM DUAL;
SELECT LTRIM('     HELLO WORLD     ') FROM DUAL;
SELECT RTRIM('     HELLO WORLD     ') FROM DUAL;
SELECT LTRIM ('JAVAHAHAJAVA', 'JAVA') FROM DUAL;
SELECT RTRIM ('JAVAHAHAAAAAAAAAAAAAAAAAAAAAAJAVA', 'JAVA') FROM DUAL;

--REPLACE 문자열 변경
SELECT REPLACE ('서울 대전 대구 부산 찍고', ' ' , '->') FROM  DUAL; -- 공백을 화살표로
SELECT REPLACE ('서울 대전 대구 부산 찍고', ' ', '') FROM DUAL; -- 공백 삭제



