--INSERT
--테이블 구조를 빠르게 확인하는 방법
DESC DEPARTMENTS;

--1. (중요) 
INSERT INTO DEPARTMENTS VALUES(280, 'DEVELOPER',NULL,1700); -- 행 삽입
SELECT * FROM DEPARTMENTS;

--DML문은 트랜잭션이 항상 기록됨 (트랜잭션 : 데이타베이스 처리 작업이 모두 완료되거나 아니면 모두 취소되게 되는 작업의 단위)
ROLLBACK;

--2. 컬럼명만 지정 가능함 (중요)
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID) VALUES (280, 'DEVELOPER', 1700);
ROLLBACK;

--INSERT구문의 서브쿼리 (단일행)
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ((SELECT MAX(DEPARTMENT_ID) +10 FROM DEPARTMENTS)/*=단일행 서브쿼리*/, 'DEV' );
ROLLBACK;

-- 서브커리 (여러 행)
CREATE TABLE EMPS AS (SELECT * FROM EMPLOYEES WHERE 1=2); -- 테이블 구조 복사
SELECT * FROM EMPS; -- 틀만 복사된 상태 -> 원본 테이블의 특정 데이터를 삽입할 예정

INSERT INTO EMPS(EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
(SELECT EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'SA_MAN');

COMMIT; --트랜잭션을 반영함 (데이터가 최종 적용됨)

--------------------------------------------------------------------------------------

--UPDATE
SELECT * FROM EMPS;
-- 업데이트 구문을 사용하기 전에는 SELECT로 해당 값이 '고유한' 행인지 확인하고 업데이트 처리해야 함
--UPDATE EMPS SET SALARY = 1000,  COMMISSION_PCT = 0.1; -- 이러면 COMMISSION_PCT행 값 전부 0.1로 바뀜, 무조건 고유한 값을 WHERE절 넣어야 함
UPDATE EMPS SET SALARY = 1000,  COMMISSION_PCT = 0.1 WHERE EMPLOYEE_ID = 148;
UPDATE EMPS SET SALARY = NVL (SALARY, 0) + 1000 WHERE EMPLOYEE_ID >= 145;


--업데이트 구문의 서브쿼리절
--1.단일값 서브쿼리
UPDATE EMPS SET SALARY = (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID  = 100) WHERE EMPLOYEE_ID = 148;
--2.여러 값 서브쿼리
UPDATE EMPS 
SET (SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
= (SELECT SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 100) WHERE EMPLOYEE_ID = 148;
--3. WHERE절에도 서브쿼리 가능함
UPDATE EMPS
SET SALARY = 1000
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG');



