CREATE TABLE `USER` (
	`MEM_NUM`	NUMBER(20)	NOT NULL,
	`ID`	NUMBER(20)	NULL,
	`PW`	VARCHAR2(30)	NULL,
	`NAME`	VARCHAR2(10)	NULL,
	`Field`	VARCHAR(255)	NULL,
	`PHONE_NUM`	NUMBER(11)	NULL,
	`GRADE`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `GRADE` (
	`GRADE`	VARCHAR(255)	NOT NULL,
	`PROFESSOR`	VARCHAR2(30)	NULL,
	`STUDENT`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `CLASS` (
	`CODE`	VARCHAR2(30)	NOT NULL,
	`CLASS_NAME`	VARCHAR2(30)	NULL,
	`TEACHER`	VARCHAR2(10)	NULL,
	`START_DATE`	DATE	NULL,
	`END_DATE`	DATE	NULL,
	`WEEK`	VARCHAR2(10)	NULL,
	`NUMBER`	NUMBER(10)	NULL,
	`NUM_CLASS`	NUMBER(10)	NULL,
	`CLASS2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `REG_LIST` (
	`MEM_NUM`	NUMBER(20)	NOT NULL,
	`CODE2`	VARCHAR2(30)	NOT NULL,
	`REG_DATE`	DATE	NULL
);

CREATE TABLE `PRACTICE` (
	`PRACTICE_NUM`	NUMBER(30)	NOT NULL,
	`CODE`	VARCHAR2(30)	NOT NULL,
	`PRACTICE_DAY`	VARCHAR(255)	NULL,
	`WRITE_DATE`	DATE	NULL,
	`ATTEND`	VARCHAR(255)	NULL,
	`ETC`	VARCHAR2(100)	NULL,
	`APPROVAL`	VARCHAR(255)	NULL
);

CREATE TABLE `COUNSELING` (
	`Key`	VARCHAR(255)	NOT NULL,
	`CODE`	VARCHAR2(30)	NOT NULL,
	`MEM_NUM`	NUMBER(20)	NOT NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL,
	`C_CONTENT`	VARCHAR2(500)	NULL,
	`FINAL_DATE`	DATE	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

CREATE TABLE `NOTIFICATION` (
	`NUMBER`	NUMBER(30)	NOT NULL,
	`B_TITLE`	VARCHAR2(30)	NULL,
	`B_DATE`	DATE	NULL,
	`MEM_NUM`	NUMBER(20)	NOT NULL
);

CREATE TABLE `CLASS_TYPE` (
	`CLASS`	VARCHAR(255)	NOT NULL,
	`CLASS1`	VARCHAR2(10)	NULL,
	`CLASS2`	VARCHAR(10)	NULL,
	`CLASS3`	VARCHAR2(10)	NULL,
	`CLASS4`	VARCHAR2(10)	NULL
);

CREATE TABLE `P_LIST` (
	`P_ITEM`	VARCHAR(255)	NULL,
	`P_ETC`	VARCHAR(255)	NULL,
	`PRACTICE_NUM`	NUMBER(30)	NOT NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`MEM_NUM`
);

ALTER TABLE `GRADE` ADD CONSTRAINT `PK_GRADE` PRIMARY KEY (
	`GRADE`
);

ALTER TABLE `CLASS` ADD CONSTRAINT `PK_CLASS` PRIMARY KEY (
	`CODE`
);

ALTER TABLE `REG_LIST` ADD CONSTRAINT `PK_REG_LIST` PRIMARY KEY (
	`MEM_NUM`,
	`CODE2`
);

ALTER TABLE `PRACTICE` ADD CONSTRAINT `PK_PRACTICE` PRIMARY KEY (
	`PRACTICE_NUM`
);

ALTER TABLE `COUNSELING` ADD CONSTRAINT `PK_COUNSELING` PRIMARY KEY (
	`Key`
);

ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (
	`NUMBER`
);

ALTER TABLE `CLASS_TYPE` ADD CONSTRAINT `PK_CLASS_TYPE` PRIMARY KEY (
	`CLASS`
);

ALTER TABLE `REG_LIST` ADD CONSTRAINT `FK_USER_TO_REG_LIST_1` FOREIGN KEY (
	`MEM_NUM`
)
REFERENCES `USER` (
	`MEM_NUM`
);

ALTER TABLE `REG_LIST` ADD CONSTRAINT `FK_CLASS_TO_REG_LIST_1` FOREIGN KEY (
	`CODE2`
)
REFERENCES `CLASS` (
	`CODE`
);

