CREATE TABLE `ORDER` (
	`ORDER_NUM`	NUMBER(30)	NOT NULL,
	`USER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `USER_ID` (
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`USER_NAME`	VARCHAR(255)	NULL,
	`PHONENUM`	NUMBER(11)	NULL
);

CREATE TABLE `PAYMENT` (
	`ORDER_NUM`	VARCHAR(255)	NOT NULL,
	`CASH`	NUMBER(99999)	NULL,
	`CARD`	NUMBER(99999)	NULL,
	`ACCOUNT`	NUMBER(99999)	NULL,
	`KAKAO`	NUMBER(99999)	NULL
);

CREATE TABLE `ADDRESS` (
	`Key`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`address`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL
);

CREATE TABLE `ORDER_DETAILE` (
	`ORDER_NUM`	VARCHAR(255)	NOT NULL,
	`ORDER_DATE`	DATE	NULL,
	`TOTAL_PRICE`	NUMBER(99999)	NULL,
	`COUNT`	NUMBER(20)	NULL,
	`Key2`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`PRODUCT_ID`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `BASKET` (
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`PRODUCT_ID`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `GOODS` (
	`PRODUCT_ID`	VARCHAR(255)	NOT NULL,
	`NAME`	VARCHAR2(30)	NULL,
	`PRICE`	NUMBER(99999)	NULL,
	`STACK`	NUMBER(30)	NULL
);

CREATE TABLE `ORDER_LIST` (
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`ORDER_NUM`	VARCHAR(255)	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

ALTER TABLE `ORDER` ADD CONSTRAINT `PK_ORDER` PRIMARY KEY (
	`ORDER_NUM`
);

ALTER TABLE `USER_ID` ADD CONSTRAINT `PK_USER_ID` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PK_PAYMENT` PRIMARY KEY (
	`ORDER_NUM`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `PK_ADDRESS` PRIMARY KEY (
	`Key`,
	`USER_ID`
);

ALTER TABLE `ORDER_DETAILE` ADD CONSTRAINT `PK_ORDER_DETAILE` PRIMARY KEY (
	`ORDER_NUM`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `PK_BASKET` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `GOODS` ADD CONSTRAINT `PK_GOODS` PRIMARY KEY (
	`PRODUCT_ID`
);

ALTER TABLE `ORDER_LIST` ADD CONSTRAINT `PK_ORDER_LIST` PRIMARY KEY (
	`USER_ID`,
	`ORDER_NUM`
);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `FK_ORDER_TO_PAYMENT_1` FOREIGN KEY (
	`ORDER_NUM`
)
REFERENCES `ORDER` (
	`ORDER_NUM`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `FK_USER_ID_TO_ADDRESS_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_ID` (
	`USER_ID`
);

ALTER TABLE `ORDER_DETAILE` ADD CONSTRAINT `FK_ORDER_TO_ORDER_DETAILE_1` FOREIGN KEY (
	`ORDER_NUM`
)
REFERENCES `ORDER` (
	`ORDER_NUM`
);

ALTER TABLE `BASKET` ADD CONSTRAINT `FK_USER_ID_TO_BASKET_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_ID` (
	`USER_ID`
);

ALTER TABLE `ORDER_LIST` ADD CONSTRAINT `FK_USER_ID_TO_ORDER_LIST_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_ID` (
	`USER_ID`
);

ALTER TABLE `ORDER_LIST` ADD CONSTRAINT `FK_ORDER_DETAILE_TO_ORDER_LIST_1` FOREIGN KEY (
	`ORDER_NUM`
)
REFERENCES `ORDER_DETAILE` (
	`ORDER_NUM`
);

