CREATE TABLE USERS (
    ID VARCHAR2 (30),
    PW VARCHAR2 (30) NOT NULL,
    NAME VARCHAR2 (30) NOT NULL,
    EMAIL VARCHAR2 (30),
    GENDER CHAR(1),
    REGDATE DATE DEFAULT SYSDATE
);
ALTER TABLE USERS ADD CONSTRAINT USERS_ID_PK PRIMARY KEY (ID); --PK
ALTER TABLE USERS ADD CONSTRAINT USERS_GENDER_CK CHECK (GENDER IN ('F', 'M')); --CK

SELECT * FROM USERS;